# Site settings
title: Monochrome | A minimal, responsive Jekyll blog theme
description: "Ning's Blog"
url: "https://chou-o-ning.github.io/web"
author:
  name: "ning"
  email: "chou.o.ning@gmail.com"
  url: "https://chou-o-ning.github.io/web"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
